APT::FTPArchive::Release::Origin "Smoke Turner";
APT::FTPArchive::Release::Label "Smoke Turner";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64 arm64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Smoke Turner packages";
